--offline 3

set serveroutput on

CREATE OR REPLACE TRIGGER LIMIT_JOBS
BEFORE INSERT OR UPDATE 
ON EMPLOYEES
FOR EACH ROW

DECLARE

N NUMBER := 30;

CURSOR C1 IS SELECT JOB_ID, COUNT(*)  AS CNT FROM EMPLOYEES GROUP BY JOB_ID;

VJOBCNT C1%ROWTYPE;

BEGIN

IF NOT (C1%ISOPEN) THEN OPEN C1; END IF;


LOOP
  EXIT WHEN C1%NOTFOUND;
  FETCH C1 INTO VJOBCNT;
  IF(VJOBCNT.CNT > N) THEN
    RAISE_APPLICATION_ERROR(-20001, 'CANNOT BE MORE THAN ' || N || ' EMPLOYEES UNDER A JOB');
  END IF;
  

END LOOP;

CLOSE C1;

END LIMIT_JOBS;
/


/*
insert into employees(employee_id,hire_date,job_id,last_name,email) values (365, '21-AUG-1995', 'SA_REP', 'BOSS', 'abc@gmail.com');
*/
