--offline 2

set serveroutput on

CREATE OR REPLACE PROCEDURE DISP_DEPT(C_ID IN VARCHAR2 )
AS 
CURSOR C1 IS 
SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME FROM DEPARTMENTS D JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID WHERE L.COUNTRY_ID = C_ID;

VDEPT C1%ROWTYPE;

BEGIN
/*
SELECT * FROM LOCATIONS;
SELECT * FROM DEPARTMENTS;*/

IF NOT(C1%ISOPEN) THEN OPEN C1;
END IF;

IF(C1%NOTFOUND) THEN DBMS_OUTPUT.PUT_LINE('NO DEPARTMENTS IN THAT COUNTRY!');
ELSE DBMS_OUTPUT.PUT_LINE('THE FOLLOWING DEPARTMETNS ARE IN COUNTRY_ID: ' || C_ID);
END IF;


LOOP
EXIT WHEN C1%NOTFOUND;
FETCH C1 INTO VDEPT;

 DBMS_OUTPUT.PUT_LINE('ID : ' || VDEPT.DEPARTMENT_ID || ' ' || 'DEPARTMENT NAME: ' || VDEPT.DEPARTMENT_NAME);

END LOOP;

CLOSE C1;

END;
/
