--offline 1

Set serveroutput on


DECLARE

MX NUMBER := -1;
MXYEAR NUMBER;

TYPE MONTHNAME IS VARRAY(12) OF VARCHAR2(3);
TYPE MONTHNUM IS VARRAY(12) OF NUMBER;

MN MONTHNAME;
MC MONTHNUM;

CURSOR C1 IS SELECT JOINYEAR, COUNT(*) CNT FROM (SELECT EXTRACT(YEAR FROM HIRE_DATE) AS JOINYEAR FROM EMPLOYEES) GROUP BY JOINYEAR;

CURSOR C2 IS SELECT YY, MM, COUNT(*) AS CNT FROM (SELECT EXTRACT(YEAR FROM HIRE_DATE) AS YY, EXTRACT(MONTH FROM HIRE_DATE) AS MM FROM EMPLOYEES)
GROUP BY (YY,MM)
ORDER BY YY,MM ASC;

EMPYEAR C1%ROWTYPE;
MONTHCNT C2%ROWTYPE;



BEGIN

IF NOT(C1%ISOPEN) THEN OPEN C1;
END IF;

LOOP
  EXIT WHEN (C1%NOTFOUND);
  
  FETCH C1 INTO EMPYEAR;
  
  IF(EMPYEAR.CNT > MX) THEN
    MX := EMPYEAR.CNT;
    MXYEAR := EMPYEAR.JOINYEAR; 
  END IF;

END LOOP;

CLOSE C1;

Dbms_Output.Put('MAXIMUM EMPLOYEES JOINED: ' || MX);
Dbms_Output.Put_Line('   IN THE YEAR: ' || MXYEAR);  


 
MN := MONTHNAME('JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC');
MC := MONTHNUM(0,0,0,0,0,0,0,0,0,0,0,0);

IF NOT (C2%ISOPEN) THEN OPEN C2;
END IF;

LOOP
  EXIT WHEN(C2%NOTFOUND);
  
  FETCH C2 INTO MONTHCNT;
  IF(MONTHCNT.YY = MXYEAR) THEN
    --Dbms_Output.Put_Line(MONTHCNT.MM || ' : ' || MONTHCNT.CNT);
    MC(MONTHCNT.MM) := MONTHCNT.CNT;
  END IF;
END LOOP;

CLOSE C2;

FOR II IN 1..12
LOOP
  Dbms_Output.Put_Line(MN(II) || ' : ' || MC(II));
END LOOP;

END;
/
